version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: fi6bOacZqdXXRAE679Iu7mXAvdr8owltFkXYajL6TonDcYhL6mXitW2gyMkW8UDf
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
deploy:
- provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: Z1DoV4FAaop88LOqNhOuUf+SUrJtH2toXU5Kx++tXpJLAYWluu4ppfdbF+SUT+7+
  on:
    branch: master
