version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
install:  
  choco install SourceLink
before_package:
  - dir "C:\projects\readonlydictionary\ReadOnlyDictionary\bin\Release\"
  - ps: sourcelink index -pr ./ReadOnlyDictionary/ReadOnlyDictionary.csproj -pp Configuration Release -u 'https://raw.githubusercontent.com/steven-dawkins/readonlydictionary/{0}/%var2%'
  
build:
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
deploy:
- provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: Z1DoV4FAaop88LOqNhOuUf+SUrJtH2toXU5Kx++tXpJLAYWluu4ppfdbF+SUT+7+
  on:
    branch: master
