version: 1.0.{build}
configuration: Release
nuget:
  project_feed: true
install:
  choco install gitlink
before_package:
  - dir "C:\projects\readonlydictionary\ReadOnlyDictionary\bin\Release\"
  - gitlink .
  
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: r727gBIOdz6e80IdNB8mL3mdMOmWXjgqIqYC54UpGKR8eD+cACLuGIojJm0LY/e4
  on:
    branch: master