version: 1.0.{build}
configuration: Release
nuget:
  project_feed: true
install:
  choco install gitlink
  choco install SourceLink
before_package:
  - dir "C:\projects\readonlydictionary\ReadOnlyDictionary\bin\Release\"
  - gitlink .
  
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: Z1DoV4FAaop88LOqNhOuUf+SUrJtH2toXU5Kx++tXpJLAYWluu4ppfdbF+SUT+7+
  on:
    branch: master
