version: 1.0.{build}
configuration: Release
nuget:
  project_feed: true
install:
  choco install gitlink
after_build:
  - dir "C:\projects\readonlydictionary\ReadOnlyDictionary\bin\Release\"
  - gitlink .
  
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: dyvkt2uVCYjR/8/fZKtUw/YgkUhZ7ETYbJKuR2ejTMSRAwOhc7KH6xNfKzpza3Y4iIEKzdU95XLvrJaEAYhJPA==
  on:
    branch: master
