version: 1.0.{build}
nuget:
  project_feed: true
install:
  choco install gitlink
after_build:
  - gitlink .
  - dir "C:\projects\readonlydictionary\ReadOnlyDictionary\bin\Release\"
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
  provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  api_key:
    secure: fR7nQXanxmQGiq05L1DurX6bIqbj6u7vh1vijX/SfgHNrEnxVPYn277Cn8VfFcip